language: node_js
node_js:
  - "12.16.2"
before_install:
  - "chmod +x npm"
install:
  - "npm install"
before_script:
  - "npm run build"
  - "npm start &"
script:
  - "npm test"
dist:
 - "trusty"
 afterfailure:
  - cat MSBuild*.failure.txt